QT       -= core gui

TARGET = zmq
TEMPLATE = lib
CONFIG += staticlib

DEFINES += ZMQ_STATIC

# The following define makes your compiler emit warnings if you use
# any Qt feature that has been marked deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

SOURCES += \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/client.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/clock.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ctx.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_client.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_mechanism_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_server.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dealer.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/decoder_allocators.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/devpoll.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dgram.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dish.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dist.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/endpoint.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/epoll.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/err.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/fq.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gather.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_client.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_mechanism_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_server.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/io_object.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/io_thread.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ip.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ip_resolver.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_listener.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/kqueue.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/lb.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mailbox.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mailbox_safe.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mechanism.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mechanism_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/metadata.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/msg.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mtrie.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/norm_engine.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/null_mechanism.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/object.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/options.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/own.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pair.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/peer.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_receiver.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_sender.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_socket.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pipe.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/plain_client.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/plain_server.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/poll.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/poller_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/polling_util.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pollset.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/precompiled.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/proxy.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pub.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pull.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/push.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/radio.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/radix_tree.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/random.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_decoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_encoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_engine.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/reaper.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/rep.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/req.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/router.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/scatter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/select.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/server.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/session_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/signaler.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socket_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socket_poller.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socks.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socks_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_connecter_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_engine_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_listener_base.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/sub.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_listener.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/thread.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/timers.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_listener.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/trie.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tweetnacl.c \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/udp_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/udp_engine.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v1_decoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v1_encoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v2_decoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v2_encoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v3_1_encoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_listener.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_connecter.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_decoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_encoder.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_engine.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_listener.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/wss_address.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/wss_engine.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/xpub.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/xsub.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zap_client.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zmq.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zmq_utils.cpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zmtp_engine.cpp

HEADERS += \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/array.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/atomic_counter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/atomic_ptr.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/blob.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/client.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/clock.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/command.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/condition_variable.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/config.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ctx.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_client.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_client_tools.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_mechanism_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/curve_server.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dbuffer.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dealer.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/decoder_allocators.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/devpoll.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dgram.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dish.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/dist.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/endpoint.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/epoll.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/err.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/fd.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/fq.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gather.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/generic_mtrie.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/generic_mtrie_impl.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_client.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_mechanism_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/gssapi_server.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/i_decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/i_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/i_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/i_mailbox.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/i_poll_events.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/io_object.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/io_thread.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ip.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ip_resolver.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ipc_listener.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/kqueue.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/lb.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/likely.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/macros.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mailbox.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mailbox_safe.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mechanism.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mechanism_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/metadata.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/msg.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mtrie.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/mutex.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/norm_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/null_mechanism.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/object.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/options.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/own.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pair.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/peer.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_receiver.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_sender.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pgm_socket.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pipe.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/plain_client.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/plain_common.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/plain_server.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/platform.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/poll.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/poller.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/poller_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/polling_util.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pollset.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/precompiled.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/proxy.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pub.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/pull.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/push.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/radio.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/radix_tree.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/random.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/raw_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/reaper.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/rep.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/req.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/router.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/scatter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/secure_allocator.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/select.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/server.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/session_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/signaler.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socket_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socket_poller.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socks.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/socks_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stdint.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_connecter_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_engine_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/stream_listener_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/sub.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tcp_listener.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/thread.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/timers.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tipc_listener.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/trie.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/tweetnacl.h \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/udp_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/udp_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v1_decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v1_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v2_decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v2_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v2_protocol.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/v3_1_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/vmci_listener.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/windows.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/wire.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_connecter.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_decoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_encoder.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_listener.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ws_protocol.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/wss_address.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/wss_engine.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/xpub.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/xsub.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ypipe.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ypipe_base.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/ypipe_conflate.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/yqueue.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zap_client.hpp \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zmq_draft.h \
    E:/Downloads/libzmq-qmake/libzmq-qmake/src/zmtp_engine.hpp

# Default rules for deployment.
unix {
    target.path = $$[QT_INSTALL_PLUGINS]/generic
}
!isEmpty(target.path): INSTALLS += target
